# Usa a imagem do Maven com Java 23 para compilar o projeto
FROM maven:3.9.6-eclipse-temurin-23 AS builder
WORKDIR /app
  
  # Copia os arquivos do projeto para o container
COPY . .
  
  # Faz o build do projeto e gera o JAR
RUN mvn clean package
  
  # Usa a imagem do OpenJDK 23 para rodar a aplicação
FROM eclipse-temurin:23-jdk-slim
WORKDIR /app
  
  # Copia o JAR gerado na etapa anterior
COPY --from=builder /app/target/frases-espiritas.jar app.jar
  
  # Expõe a porta da aplicação
EXPOSE 8080
  
  # Define o comando para rodar a aplicação
ENTRYPOINT ["java", "-jar", "app.jar"]