services:
    # Serviço do PostgreSQL
    postgres:
        image: postgres:15-alpine
        container_name: postgres
        environment:
            POSTGRES_DB: frases-espiritas
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
        ports:
            - "5432:5432"
        volumes:
            - db_data:/var/lib/postgresql/data

    # Serviço da aplicação Spring Boot
    spring:
        build: .
        container_name: spring
        ports:
            - "8080:8080"
        depends_on:
            - postgres

volumes:
    db_data: